-- AtlasLoot loot tables zhTW locale file
-- NOTE: THIS FILE IS AUTO-GENERATED BY A TOOL, ANY MANUALLY CHANGE MIGHT BE OVERWRITTEN.
-- $Id: WorldPvP.tw.lua 257 2008-07-16 15:36:58Z kurax $

if GetLocale() == "zhTW" then
local Process = function(category,check,data) if not AtlasLoot_Data["AtlasLootWorldPvPItems"][category] or #AtlasLoot_Data["AtlasLootWorldPvPItems"][category] ~= check then return end for i = 1,#data do if(data[i] and data[i]~="") then AtlasLoot_Data["AtlasLootWorldPvPItems"][category][i][3] = data[i] end end data = nil end
Process("Hellfire",22,{"=q3=勝利指環","=q3=倒刺深綠橄欖石","=q3=強大的血石榴石","","","=q1=榮譽堡壘徽章","=q1=榮譽堡印記","","","","","","","","","=q3=勝利環戒","=q3=鋸型深綠橄欖石","=q3=突出的血石榴石","","","=q1=索爾瑪徽章","=q1=索爾瑪印記"})
Process("Nagrand1",29,{"=q4=黑色塔巴克坐騎韁繩","=q4=高尚的神秘黎明石","=q3=祭師護腿","=q3=巡夢者護腿","=q3=巡影者護腿","=q3=神射手的腿甲","=q3=風暴碎裂護腿","=q3=復仇者的腿鎧","=q3=殺戮者護腿","","=q3=設計圖:神秘的黎明石","","","=q2=哈剌戰鬥徽章","","=q4=黑色塔巴克戰騎韁繩","=q3=哈剌尼盆地背包","=q3=祭師束帶","=q3=巡夢者束帶","=q3=巡影者束帶","=q3=神射手的腰帶","=q3=風暴碎裂束腰","=q3=復仇者護腰","=q3=殺戮者護腰","","=q3=設計圖:穩固的泰拉寶石","=q1=配方:鐵膚藥劑","","=q2=哈剌研究徽章"})
Process("Nagrand2",22,{"=q3=哈剌尼剃刃矢","=q1=哈剌尼威士忌","","","=q3=阿曼席歐先生的心形寶石","=q2=哈剌尼巨刃劍","=q2=復仇飛刃","","","","","","","","","=q3=哈剌尼邪惡射擊","","","","=q3=羅吉哥先生的心形寶石","=q2=阿卡迪恩巨刃劍","=q2=鋒利圓盤"})
Process("Terokkar",25,{"=q4=驅魔者指環","=q3=迅捷的星火鑽石","=q3=驅魔者懼紋兜帽","=q3=驅魔者龍皮頭盔","=q3=驅魔者龍革頭盔","=q3=驅魔者鎖鍊頭盔","=q3=驅魔者綴甲頭盔","=q3=驅魔者綴鱗頭盔","","=q1=奧奇奈治療藥水","","=q1=鬼靈裂片","","","","=q4=驅魔者之印","=q3=迅捷的風火鑽石","=q3=驅魔者絲質兜帽","=q3=驅魔者皮革頭盔","=q3=驅魔者鍊甲頭盔","=q3=驅魔者鎖甲頭盔","=q3=驅魔者鎧甲頭盔","","","=q1=奧奇奈法力藥水"})
Process("Zangarmarsh",22,{"=q3=兇蠻塑像","=q3=衝擊圖騰","=q3=挑戰印記","=q3=終極之鋒","=q3=易燃棍棒","","=q1=榮譽堡印記","","","","","","","","","=q3=狂熱聖契","=q3=征服印記","=q3=復仇印記","=q3=碎裂標靶之弓","","","=q1=索爾瑪印記"})
end